graph TB
    subgraph "Client Side"
        Menu[DPointShopMenu<br/>Main Shop Interface]
        Inspector[DPointShopInspector<br/>Preview Panel]
        CustomPanel[PSItemCustomizationPanel<br/>Unified Customization]
        ItemPanel[DPointShopItem<br/>Item Display]
        
        Menu -->|Select Category| CategoryGrid[Category Grid<br/>Scrollable 4-col]
        Menu -->|Populate Items| ItemGrid[Item Grid<br/>Scrollable 4-col]
        ItemGrid -->|Create| ItemPanel
        
        ItemPanel -->|Right Click:<br/>Inspect| Inspector
        ItemPanel -->|Right Click:<br/>Equip| ClientEquip[cl_player_extension<br/>PS_EquipItem]
        ItemPanel -->|Right Click:<br/>Customize| CustomPanel
        
        Inspector -->|Preview Model| ClientModel[ClientsideModel<br/>Preview Entity]
        Inspector -->|Camera Control| CalcView[CalcView Hook<br/>Spherical Coordinates]
        
        CustomPanel -->|Playermodel| PMControls[Bodygroups<br/>Skin<br/>Player Color]
        CustomPanel -->|Accessory| AccControls[Position XYZ<br/>Rotation<br/>Scale<br/>Color]
        CustomPanel -->|Apply| NetSend[net.Start<br/>PS_ApplyCustomization]
    end
    
    subgraph "Network Layer"
        NetSend -->|Send to Server| NetReceive[net.Receive<br/>PS_ApplyCustomization]
        ClientEquip -->|net.Start| ServerEquip[net.Receive<br/>PS_EquipItem]
    end
    
    subgraph "Server Side"
        NetReceive -->|Rate Limit Check| RateLimit{Rate Limiter<br/>5 req/10sec}
        RateLimit -->|Approved| Sanitize[Data Sanitization<br/>Validate values]
        RateLimit -->|Denied| Notify[PS_Notify<br/>Too many requests]
        
        Sanitize -->|Playermodel| PMApply[ApplyModelSettings<br/>SetModel/Skin/Bodygroups]
        Sanitize -->|Accessory| AccApply[ModifyClientsideModel<br/>Position/Scale/Rotation]
        
        PMApply -->|Save| Storage
        AccApply -->|Save| Storage
        
        ServerEquip -->|Check Slot| SlotCheck{Same Slot?}
        SlotCheck -->|Yes| Holster[PS_HolsterItem<br/>Unequip old item]
        SlotCheck -->|No| TypeCheck{Playermodel?}
        TypeCheck -->|Yes| PMCheck[Unequip other<br/>playermodels]
        TypeCheck -->|No| EquipItem
        Holster --> EquipItem[PS_EquipItem<br/>Mark equipped]
        PMCheck --> EquipItem
        
        EquipItem -->|OnEquip| ItemBase[Item Base<br/>OnEquip/OnHolster]
        ItemBase -->|Playermodel| PMBase[sh_playermodel_base<br/>ApplyModelSettings]
        ItemBase -->|Accessory| AccBase[sh_accessory_base<br/>CreateClientsideModel]
    end
    
    subgraph "Data Storage"
        Storage[(Unified Backend<br/>PS_PLAYERMODEL_CUSTOMIZATIONS<br/>PS_ACCESSORY_CUSTOMIZATIONS)]
        Storage -->|Provider| Provider{Storage Provider}
        Provider -->|JSON| JSON[json.lua]
        Provider -->|MySQL| MySQL[mysql.lua]
        Provider -->|FlatFile| FlatFile[flatfile.lua]
        Provider -->|PData| PData[pdata.lua]
    end
    
    subgraph "Item Types"
        PMBase -->|Modify| PMCustom[Playermodel Items<br/>TYPE: playermodel<br/>Bodygroups/Skin/Color]
        AccBase -->|Modify| AccCustom[Accessory Items<br/>TYPE: accessory<br/>Bone/Attachment/Model]
    end
    
    Storage -.->|Load on Join| PlayerData[Player Data<br/>PS_Items table]
    PlayerData -.->|Send to Client| ClientData[LocalPlayer<br/>PS_Items]
    ClientData -.->|Populate| Menu

    style Menu fill:#60a0c8
    style Inspector fill:#60a0c8
    style CustomPanel fill:#60a0c8
    style Storage fill:#4a7c59
    style RateLimit fill:#c86060
    style Sanitize fill:#c8a060
